# Generated by Django 3.2.13 on 2022-05-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20220511_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='faculty',
        ),
        migrations.AddField(
            model_name='branch',
            name='faculty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='faculty.faculty'),
            preserve_default=False,
        ),
    ]
