# Generated by Django 3.2.13 on 2022-04-22 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mid_name', models.CharField(blank=True, default='', max_length=50)),
                ('cnp', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
    ]
