# Generated by Django 3.2.13 on 2022-04-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cnp',
            field=models.PositiveIntegerField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
