# Generated by Django 3.2.13 on 2022-04-22 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_cnp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mid_name', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(max_length=250, unique=True)),
            ],
        ),
    ]
