# Generated by Django 3.2.13 on 2022-05-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20220511_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mid_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
