# Generated by Django 3.2.13 on 2022-04-22 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_alter_student_cnp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('detail', models.CharField(max_length=500)),
                ('due_date', models.DateField(blank=True)),
                ('type', models.CharField(choices=[('Reminder', 'Reminder'), ('Revision', 'Revision')], default='Reminder', max_length=15)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
