# Generated by Django 3.2.13 on 2022-05-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltask',
            old_name='student_id',
            new_name='student',
        ),
    ]
